# Generated by Django 3.2.8 on 2021-11-10 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='summary',
        ),
    ]
