# Generated by Django 3.2.8 on 2021-10-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='id')),
                ('displayName', models.CharField(max_length=40, verbose_name='displayName')),
                ('github', models.URLField(max_length=60, verbose_name='github')),
                ('profileImage', models.URLField(verbose_name='profileImage')),
            ],
        ),
    ]
