# Generated by Django 3.2.8 on 2021-11-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='netloc',
            field=models.CharField(default='', max_length=100, verbose_name='netloc of node'),
        ),
    ]
