# Generated by Django 3.2.8 on 2021-11-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='description',
            field=models.CharField(blank=True, default=False, max_length=300),
        ),
    ]
