# Generated by Django 3.2.8 on 2021-12-03 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='authRequiredIncoming',
        ),
        migrations.RemoveField(
            model_name='node',
            name='authRequiredOutgoing',
        ),
    ]
