# Generated by Django 3.2.8 on 2021-11-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_node_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='url',
            field=models.URLField(unique=True, verbose_name='url of node'),
        ),
    ]
