# Generated by Django 3.2.8 on 2021-10-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='userName',
            field=models.CharField(default='defaultName', max_length=40, unique=True, verbose_name='userName'),
        ),
        migrations.AlterField(
            model_name='author',
            name='displayName',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
