# Generated by Django 3.2.8 on 2021-11-25 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='host',
        ),
        migrations.RemoveField(
            model_name='author',
            name='isLocalUser',
        ),
    ]
