# Generated by Django 3.2.8 on 2021-11-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20211124_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
