# Generated by Django 3.2.8 on 2021-10-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20211027_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='isLocalUser',
            field=models.BooleanField(default=True),
        ),
    ]
