# Generated by Django 3.2.8 on 2021-11-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20211101_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contentType',
            field=models.CharField(choices=[('M', 'text/markdown'), ('P', 'text/plain')], default='P', max_length=1, verbose_name='contentType'),
        ),
    ]
