# Generated by Django 3.2.7 on 2021-10-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_alter_comment_contenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contentType',
            field=models.CharField(choices=[('M', 'text/markdown'), ('P', 'text/plain')], default='P', max_length=1, verbose_name='contentType'),
        ),
    ]
