# Generated by Django 3.2.8 on 2021-10-29 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_posts_visibility'),
        ('comment', '0007_alter_comment_contenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contentType',
            field=models.CharField(choices=[('M', 'text/markdown'), ('P', 'text/plain')], default='P', max_length=1, verbose_name='contentType'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='posts.posts'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
