# Generated by Django 3.2.8 on 2021-10-29 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_auto_20211029_0029'),
        ('comment', '0008_auto_20211029_1323'),
        ('comment', '0012_auto_20211029_1207'),
    ]

    operations = [
    ]
