# Generated by Django 3.2.7 on 2021-10-29 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_alter_comment_contenttype'),
        ('comment', '0012_auto_20211029_1207'),
    ]

    operations = [
    ]
