# Generated by Django 3.2.7 on 2021-10-29 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0013_merge_20211029_1329'),
        ('comment', '0013_merge_20211029_2032'),
    ]

    operations = [
    ]
