# Generated by Django 3.2.8 on 2021-11-26 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='postsManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100, verbose_name='title')),
                ('visibility', models.CharField(choices=[('PR', 'PRIVATE'), ('PU', 'PUBLIC')], default='PU', max_length=8)),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='description')),
                ('content', models.TextField(blank=True, max_length=400, verbose_name='content')),
                ('contentType', models.CharField(choices=[('plain', 'text/plain'), ('png', 'image/png;base64'), ('jpeg', 'image/jpeg;base64'), ('markdown', 'text/markdown'), ('app', 'application/base64')], default='plain', max_length=20)),
                ('comments', models.TextField(editable=False)),
                ('source', models.URLField(editable=False)),
                ('origin', models.URLField(editable=False)),
                ('unlisted', models.BooleanField(default=False)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('count', models.IntegerField(default=0)),
                ('categories', models.CharField(max_length=200)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
