# Generated by Django 3.2.8 on 2021-11-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('png', 'image/png;base64'), ('jpeg', 'image/jpeg;base64'), ('app', 'application/base64'), ('plain', 'text/plain'), ('markdown', 'text/markdown')], default='plain', max_length=20),
        ),
    ]
