# Generated by Django 3.2.8 on 2021-11-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_contenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('markdown', 'text/markdown'), ('app', 'application/base64'), ('plain', 'text/plain'), ('jpeg', 'image/jpeg;base64'), ('png', 'image/png;base64')], default='plain', max_length=20),
        ),
    ]
