# Generated by Django 3.2.8 on 2021-12-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211201_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('markdown', 'text/markdown'), ('png', 'image/png;base64'), ('plain', 'text/plain'), ('jpeg', 'image/jpeg;base64'), ('app', 'application/base64')], default='plain', max_length=20),
        ),
    ]
