# Generated by Django 3.2.8 on 2021-10-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211029_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmanager',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
