# Generated by Django 3.2.8 on 2021-10-29 20:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_auto_20211029_1323'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_alter_posts_visibility'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='posts',
            new_name='Post',
        ),
    ]
