# Generated by Django 3.2.8 on 2021-10-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_postsmanager_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='visibility',
            field=models.CharField(choices=[('PU', 'PUBLIC'), ('PR', 'PRIVATE')], default='PU', max_length=8),
        ),
    ]
