# Generated by Django 3.2.8 on 2021-11-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20211125_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('png', 'image/png;base64'), ('markdown', 'text/markdown'), ('plain', 'text/plain'), ('jpeg', 'image/jpeg;base64'), ('app', 'application/base64')], default='plain', max_length=20),
        ),
    ]
