# Generated by Django 3.2.9 on 2021-11-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20211126_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('jpeg', 'image/jpeg;base64'), ('markdown', 'text/markdown'), ('png', 'image/png;base64'), ('app', 'application/base64'), ('plain', 'text/plain')], default='plain', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PR', 'PRIVATE'), ('PU', 'PUBLIC')], default='PU', max_length=8),
        ),
    ]
