# Generated by Django 3.2.8 on 2021-12-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20211201_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('png', 'image/png;base64'), ('jpeg', 'image/jpeg;base64'), ('app', 'application/base64'), ('markdown', 'text/markdown'), ('plain', 'text/plain')], default='plain', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PU', 'PUBLIC'), ('PR', 'PRIVATE')], default='PU', max_length=8),
        ),
    ]
