# Generated by Django 3.1.6 on 2021-11-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20211101_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, max_length=400, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('jpeg', 'image/jpeg;base64'), ('app', 'application/base64'), ('png', 'image/png;base64'), ('markdown', 'text/markdown'), ('plain', 'text/plain')], default='plain', max_length=20),
        ),
    ]
