# Generated by Django 3.2.8 on 2021-11-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20211126_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('png', 'image/png;base64'), ('plain', 'text/plain'), ('app', 'application/base64'), ('jpeg', 'image/jpeg;base64'), ('markdown', 'text/markdown')], default='plain', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PR', 'PRIVATE'), ('PU', 'PUBLIC')], default='PU', max_length=8),
        ),
    ]
