# Generated by Django 3.1.6 on 2021-10-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_posts_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmanager',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
