# Generated by Django 3.1.6 on 2021-11-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20211101_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('plain', 'text/plain'), ('png', 'image/png;base64'), ('jpeg', 'image/jpeg;base64'), ('app', 'application/base64'), ('markdown', 'text/markdown')], default='plain', max_length=20),
        ),
    ]
