# Generated by Django 3.1.6 on 2021-10-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20211029_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='visibility',
            field=models.CharField(choices=[('PR', 'PRIVATE'), ('PU', 'PUBLIC')], default='PU', max_length=8),
        ),
    ]
