# Generated by Django 3.2.8 on 2021-11-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20211125_1509'),
        ('posts', '0007_auto_20211126_0431'),
    ]

    operations = [
    ]
