# Generated by Django 3.1.6 on 2021-11-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20211101_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('app', 'application/base64'), ('jpeg', 'image/jpeg;base64'), ('png', 'image/png;base64'), ('markdown', 'text/markdown'), ('plain', 'text/plain')], default='plain', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='title'),
        ),
    ]
