# Generated by Django 3.2.8 on 2021-11-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_merge_0005_auto_20211125_1509_0007_auto_20211126_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('png', 'image/png;base64'), ('app', 'application/base64'), ('jpeg', 'image/jpeg;base64'), ('plain', 'text/plain'), ('markdown', 'text/markdown')], default='plain', max_length=20),
        ),
    ]
