# Generated by Django 3.2.8 on 2021-11-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20211101_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('markdown', 'text/markdown'), ('png', 'image/png;base64'), ('jpeg', 'image/jpeg;base64'), ('app', 'application/base64'), ('plain', 'text/plain')], default='plain', max_length=20),
        ),
    ]
