# Generated by Django 3.2.9 on 2021-11-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20211126_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('jpeg', 'image/jpeg;base64'), ('markdown', 'text/markdown'), ('png', 'image/png;base64'), ('app', 'application/base64'), ('plain', 'text/plain')], default='plain', max_length=20),
        ),
    ]
