# Generated by Django 3.1.6 on 2021-10-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20211029_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='contentType',
            field=models.CharField(choices=[('jpeg', 'image/jpeg;base64'), ('png', 'image/png;base64'), ('plain', 'text/plain'), ('app', 'application/base64'), ('markdown', 'text/markdown')], default='plain', max_length=20),
        ),
        migrations.AddField(
            model_name='posts',
            name='descripion',
            field=models.TextField(blank=True, max_length=100, verbose_name='description'),
        ),
    ]
