# Generated by Django 3.2.8 on 2021-11-26 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_contenttype'),
        ('posts', '0010_auto_20211126_1222'),
    ]

    operations = [
    ]
