# Generated by Django 3.1.6 on 2021-10-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20211029_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='contentType',
            field=models.CharField(choices=[('markdown', 'text/markdown'), ('jpeg', 'image/jpeg;base64'), ('png', 'image/png;base64'), ('app', 'application/base64'), ('plain', 'text/plain')], default='plain', max_length=20),
        ),
        migrations.AlterField(
            model_name='posts',
            name='descripion',
            field=models.CharField(blank=True, max_length=100, verbose_name='description'),
        ),
    ]
