# Generated by Django 3.2.8 on 2021-11-29 22:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_contenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('plain', 'text/plain'), ('jpeg', 'image/jpeg;base64'), ('markdown', 'text/markdown'), ('png', 'image/png;base64'), ('app', 'application/base64')], default='plain', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
