# Generated by Django 3.2.8 on 2021-11-30 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20211129_1951'),
        ('posts', '0011_auto_20211129_1440'),
    ]

    operations = [
    ]
