# Generated by Django 3.1.6 on 2021-10-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20211029_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='descripion',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='posts',
            name='contentType',
            field=models.CharField(choices=[('plain', 'text/plain'), ('app', 'application/base64'), ('png', 'image/png;base64'), ('markdown', 'text/markdown'), ('jpeg', 'image/jpeg;base64')], default='plain', max_length=20),
        ),
    ]
