# Generated by Django 3.2.8 on 2021-11-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_merge_0005_auto_20211129_1951_0011_auto_20211129_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('png', 'image/png;base64'), ('markdown', 'text/markdown'), ('jpeg', 'image/jpeg;base64'), ('plain', 'text/plain'), ('app', 'application/base64')], default='plain', max_length=20),
        ),
    ]
