# Generated by Django 3.2.8 on 2021-11-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20211109_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('plain', 'text/plain'), ('png', 'image/png;base64'), ('markdown', 'text/markdown'), ('app', 'application/base64'), ('jpeg', 'image/jpeg;base64')], default='plain', max_length=20),
        ),
    ]
