# Generated by Django 3.2.8 on 2021-11-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_post_contenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('markdown', 'text/markdown'), ('plain', 'text/plain'), ('png', 'image/png;base64'), ('app', 'application/base64'), ('jpeg', 'image/jpeg;base64')], default='plain', max_length=20),
        ),
    ]
