# Generated by Django 3.2.8 on 2021-10-29 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_posts_post'),
        ('posts', '0013_auto_20211029_1207'),
    ]

    operations = [
    ]
