# Generated by Django 3.2.8 on 2021-11-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_post_contenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('jpeg', 'image/jpeg;base64'), ('png', 'image/png;base64'), ('plain', 'text/plain'), ('markdown', 'text/markdown'), ('app', 'application/base64')], default='plain', max_length=20),
        ),
    ]
