# Generated by Django 3.2.8 on 2021-11-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20211123_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('markdown', 'text/markdown'), ('plain', 'text/plain'), ('png', 'image/png;base64'), ('jpeg', 'image/jpeg;base64'), ('app', 'application/base64')], default='plain', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PR', 'PRIVATE'), ('PU', 'PUBLIC')], default='PU', max_length=8),
        ),
    ]
