# Generated by Django 3.2.8 on 2021-11-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20211125_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('plain', 'text/plain'), ('app', 'application/base64'), ('png', 'image/png;base64'), ('jpeg', 'image/jpeg;base64'), ('markdown', 'text/markdown')], default='plain', max_length=20),
        ),
    ]
