# Generated by Django 3.2.8 on 2021-11-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxitem',
            name='type',
            field=models.CharField(choices=[('L', 'Like'), ('P', 'Post'), ('F', 'Follow')], default='P', max_length=1),
        ),
    ]
