# Generated by Django 3.2.8 on 2021-11-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0009_alter_inboxitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxitem',
            name='type',
            field=models.CharField(choices=[('P', 'Post'), ('L', 'Like'), ('F', 'Follow')], default='P', max_length=1),
        ),
    ]
