# Generated by Django 3.2.9 on 2021-11-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Followers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow_request',
            name='requestor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='follower',
            name='sender',
            field=models.CharField(max_length=100),
        ),
    ]
