# Generated by Django 3.2.8 on 2021-12-05 06:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Followers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
