# Generated by Django 3.1.6 on 2021-11-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Followers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow_request',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
