# Generated by Django 3.2.7 on 2021-10-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Followers', '0002_auto_20211028_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow_request',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
