# Generated by Django 3.1.6 on 2021-10-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Followers', '0003_alter_follow_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow_request',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
