# Generated by Django 3.2.8 on 2021-10-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Followers', '0006_auto_20211029_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow_request',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
